import type { Schema } from "@remix-run/data-schema";

interface CollectionInfo {
    schema: Schema<unknown>;
}

export function generateTypes(
    collections: Record<string, CollectionInfo>,
    configPath: string,
): string {
    const collectionEntries = Object.entries(collections);

    const entryMapEntries = collectionEntries
        .map(([name]) => {
            return `		${name}: {
			[id: string]: import("${CONTENT_LAYER_API_PATH}").DataEntry<
				import("@remix-run/data-schema").InferOutput<
					_ResolveSchema<_Collections["${name}"]["schema"]>
				>
			> & {
				collection: "${name}";
			};
		};`;
        })
        .join("\n");

    return `// Auto-generated by content-layer
// Do not edit this file manually

declare module "sprinkles:content" {
	type _Collections = typeof import("${configPath}").collections;
	type _ResolveSchema<T> = T extends (...args: any[]) => infer R ? R : T;

	interface ContentEntryMap {
${entryMapEntries}
	}

	type Flatten<T> = T extends { [K: string]: infer U } ? U : never;
	type CollectionKey = keyof ContentEntryMap;
	type CollectionEntry<C extends CollectionKey> = Flatten<ContentEntryMap[C]>;

	type ReferenceContentEntry<
		C extends keyof ContentEntryMap,
		E extends ContentEntryMap[C] | (string & {}) = string,
	> = {
		collection: C;
		id: E;
	};

	export function getCollection<C extends CollectionKey>(
		collection: C,
		filter?: (entry: CollectionEntry<C>) => unknown,
	): Promise<CollectionEntry<C>[]>;

	export function getEntry<C extends CollectionKey>(
		collection: C,
		slug: string,
	): Promise<CollectionEntry<C> | undefined>;

	export function getEntry<C extends CollectionKey>(
		entry: ReferenceContentEntry<C>,
	): Promise<CollectionEntry<C> | undefined>;

	export function getEntries<C extends CollectionKey>(
		entries: ReferenceContentEntry<C>[],
	): Promise<CollectionEntry<C>[]>;

	export function render<C extends CollectionKey>(
		entry: CollectionEntry<C>,
	): Promise<import("${CONTENT_LAYER_API_PATH}").RenderedEntry>;

	export function defineCollection<
		S extends
			| import("@remix-run/data-schema").Schema<any, any>
			| ((
					ctx: import("${CONTENT_LAYER_API_PATH}").SchemaContext,
				) => import("@remix-run/data-schema").Schema<any, any>),
	>(
		input: { loader: import("${CONTENT_LAYER_API_PATH}").ContentLoader; schema: S },
	): { loader: import("${CONTENT_LAYER_API_PATH}").ContentLoader; schema: S };

	export function reference(
		collection: string,
	): import("@remix-run/data-schema").Schema<string, { collection: string; id: string }>;
}
`;
}

const CONTENT_LAYER_API_PATH = "../../content-layer/api.ts";
